const styles = {
  body: {
    margin: 0,
    padding: 0,
    fontFamily: "Arial, sans-serif",
    backgroundColor: "#f5f5f5",
  },
  nav: {
    backgroundColor: "#2196f3",
    padding: "1rem 2rem",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
  },
  navLinks: {
    display: "flex",
    gap: "2rem",
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  navLink: {
    textDecoration: "none",
    color: "#fff",
    fontWeight: "bold",
    padding: "0.5rem 1rem",
    borderRadius: "4px",
  },
  container: {
    maxWidth: "800px",
    margin: "2rem auto",
    padding: "2rem",
    backgroundColor: "#fff",
    borderRadius: "8px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
  },
  title: {
    fontSize: "2.5rem",
    marginBottom: "1.5rem",
    color: "#333",
    textAlign: "center",
  },
  infoBox: {
    backgroundColor: "red",
    border: "2px solid #2196f3",
    borderRadius: "8px",
    padding: "1.5rem",
    marginBottom: "2rem",
  },
  inputGroup: {
    display: "flex",
    marginBottom: "2rem",
    gap: "1rem",
  },
  input: {
    flex: 1,
    padding: "0.75rem",
    fontSize: "1rem",
    border: "2px solid #ddd",
    borderRadius: "4px",
  },
  button: {
    padding: "0.75rem 2rem",
    fontSize: "1rem",
    backgroundColor: "#2196f3",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontWeight: "bold",
  },
  exampleBtn: {
    display: "block",
    width: "100%",
    padding: "0.75rem",
    margin: "0.5rem 0",
    backgroundColor: "#f5f5f5",
    border: "2px solid #ddd",
    borderRadius: "4px",
    cursor: "pointer",
    textAlign: "left",
    fontSize: "1rem",
  },
  resultBox: {
    backgroundColor: "#e8f5e9",
    border: "3px solid #4caf50",
    borderRadius: "8px",
    padding: "2rem",
    textAlign: "center",
    marginBottom: "2rem",
  },
  errorBox: {
    backgroundColor: "#ffebee",
    border: "3px solid #f44336",
    borderRadius: "8px",
    padding: "2rem",
    textAlign: "center",
    marginBottom: "2rem",
    color: "#c62828",
  },
  resultNumber: {
    fontSize: "4rem",
    fontWeight: "bold",
    color: "#2e7d32",
    margin: "1rem 0",
  },
  expression: {
    fontSize: "2rem",
    fontFamily: "monospace",
    marginBottom: "1rem",
    color: "#555",
  },
  backButton: {
    padding: "0.75rem 2rem",
    fontSize: "1rem",
    backgroundColor: "#757575",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontWeight: "bold",
    marginRight: "1rem",
  },
  code: {
    backgroundColor: "black",
    padding: "4px 8px",
    borderRadius: "4px",
    fontFamily: "monospace",
    fontSize: "0.9rem",
  },
};

export default styles;
